# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='datetime',
        ),
    ]
